// Clerk appearance — hardcoded light mode values in variables (Clerk needs resolved
// colors for its color-mix() scale generation). Dark mode handled by --clerk-color-*
// CSS custom properties in globals.css that override these at the CSS level.
export const clerkAppearance = {
  variables: {
    colorPrimary: 'hsl(247 52% 25%)',
    colorBackground: 'hsl(220 40% 98%)',
    colorInputBackground: 'hsl(0 0% 100%)',
    colorInputText: 'hsl(247 33% 15%)',
    colorText: 'hsl(247 33% 15%)',
    colorTextSecondary: 'hsl(220 10% 36%)',
    colorDanger: 'hsl(0 72% 51%)',
    colorSuccess: 'hsl(174 72% 38%)',
    colorWarning: 'hsl(32 95% 43%)',
    fontFamily: 'var(--font-inter), system-ui, sans-serif',
    borderRadius: '0.75rem',
    spacingUnit: '0.25rem',
  },
  elements: {
    rootBox: 'w-full',
    cardBox: [
      'shadow-sm rounded-xl',
      'border border-[hsl(var(--border))]',
      'bg-[hsl(var(--surface))]',
    ].join(' '),
    card: 'bg-[hsl(var(--surface))] text-[hsl(var(--foreground))]',
    headerTitle: 'text-[hsl(var(--foreground))]',
    headerSubtitle: 'text-[hsl(var(--muted-foreground))]',
    socialButtonsBlockButton: [
      'border rounded-lg',
      'border-[hsl(var(--border))]',
      'bg-[hsl(var(--surface))]',
      'text-[hsl(var(--foreground))]',
      'hover:bg-[hsl(var(--muted))]',
    ].join(' '),
    socialButtonsBlockButtonText: 'text-[hsl(var(--foreground))]',
    formFieldInput: [
      'rounded-lg',
      'bg-[hsl(var(--surface))]',
      'text-[hsl(var(--foreground))]',
      'border-[hsl(var(--input))]',
      'placeholder:text-[hsl(var(--muted-foreground))]',
    ].join(' '),
    formFieldLabel: 'text-[hsl(var(--foreground))]',
    formButtonPrimary: 'text-white dark:text-white',
    footerActionText: 'text-[hsl(var(--muted-foreground))] dark:text-[hsl(225_8%_40%)]',
    footerActionLink: 'text-[hsl(var(--primary))] hover:text-[hsl(var(--primary-hover))] dark:text-[hsl(225_8%_40%)] dark:hover:text-[hsl(225_8%_50%)]',
    footer: 'dark:[&_*]:text-[hsl(225_8%_40%)]',
    navbarButton: 'text-[hsl(var(--foreground))]',
    dividerLine: 'bg-[hsl(var(--border))]',
    dividerText: 'text-[hsl(var(--muted-foreground))]',
    identityPreview: 'bg-[hsl(var(--muted))] border-[hsl(var(--border))]',
    identityPreviewText: 'text-[hsl(var(--foreground))]',
    alertText: 'text-[hsl(var(--foreground))]',
    formFieldErrorText: 'text-[hsl(var(--destructive))]',
    formResendCodeLink: 'text-[hsl(var(--primary))]',
    otpCodeFieldInput: [
      'rounded-lg',
      'bg-[hsl(var(--surface))]',
      'text-[hsl(var(--foreground))]',
      'border-[hsl(var(--input))]',
    ].join(' '),
  },
  layout: {
    socialButtonsVariant: 'blockButton' as const,
    logoImageUrl: `${process.env.NEXT_PUBLIC_SITE_URL || ''}/logo-msn.svg`,
  },
}
